project:
  type: website
  output-dir: docs

website:
  title: "SIASS - L3 Sciences Sociales"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - text: "Introduction"
        href: slides_intro.qmd
      - href: slides_seq1.qmd
        text: "SÃ©quence 1"

format:
  html:
    theme: cosmo
    toc: true